services:
  web:
    image: flaskapp:v2
    ports:
      - "5000:5000"
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
      MYSQL_HOST: db
      MYSQL_DB: pay_app_db
      SECRET_KEY: mydevopssecret123
    depends_on:
      - db
    networks:
      - 2-tier

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: pay_app_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - 2-tier

volumes:
  mysql-data:

networks:
  2-tier: